# Generated by Django 5.1.1 on 2024-09-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('emp_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('OPERATIONS', 'OPERATIONS'), ('DEVELOPMENT', 'DEVELOPMENT')], max_length=20)),
                ('salary', models.CharField(max_length=7)),
            ],
        ),
    ]
